version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./
    volumes:
      - images-data:/app/public
    ports:
      - 80:80
    depends_on:
      - mongodb

volumes:
  mongo-data:
  images-data: